### ISSUE TITLE
Minimal IAM usage error

### ISSUE THREAD

**Issue by oytunyuksel** [azatsafin/terraform-aws-wireguard#2]
Hi @azatsafin,

Thank you for this module but i have a problem.

When i try with mininal-iam config, i'm getting below error? What is the problem, do you have any idea @azatsafin?

`
╷
│ Warning: Argument is deprecated
│ 
│   with module.cognito_auth_redirect.aws_s3_bucket_object.lambda_package,
│   on .terraform/modules/cognito_auth_redirect/main.tf line 115, in resource "aws_s3_bucket_object" "lambda_package":
│  115:   bucket        = var.s3_bucket
│ 
│ Use the aws_s3_object resource instead
│ 
│ (and 9 more similar warnings elsewhere)
╵
╷
│ Error: Invalid index
│ 
│   on cognito.tf line 17, in module "wg_cognito_user_pool":
│   17:         "${module.api_gateway_cognito[0].apigatewayv2_api_api_endpoint}/cognito-auth-redirect"
│     ├────────────────
│     │ module.api_gateway_cognito is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
╵
╷
│ Error: Invalid index
│ 
│   on cognito.tf line 19, in module "wg_cognito_user_pool":
│   19:       default_redirect_uri                 = "${module.api_gateway_cognito[0].apigatewayv2_api_api_endpoint}/cognito-auth-redirect"
│     ├────────────────
│     │ module.api_gateway_cognito is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
╵
Releasing state lock. This may take a few moments...
ERRO[0043] 1 error occurred:
`
I'm using terraform via terragrunt by the way.

**Comment by BrightNext** [comment]
NO I don't know

**Comment by azatsafin** [comment]
Hello @oytunyuksel 
I've checked minimal-iam example, the example itself had typo, i've fixed it in last release.
Could you please next time add your configuration details in your issue description.

**Comment by azatsafin** [comment]
No comments so far

**Comment by oytunyuksel** [comment]
Hi @azatsafin,

I upgraded version to 0.2.3 and now i'm getting different error. Error is below:

`Error: Error building docker image: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile`

I'm using this config:

`instance_type                = "t2.nano"
  wg_group_name                = "VPN"
  vpc_id                       = "MY_VPC_ID"
  wg_admin_email               = "MY_EMAIL"`
